INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (1,'Boutiques',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (2,'Brocante',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (3,'Supermarché',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (4,'Epicerie',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (5,'Blanchisseries et Pressings',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (6,'Centre Commercial',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (7,'Maison et Jardin',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (8,'Hifi, téléphonie',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (9,'Fleuriste',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (10,'Boulangerie, Pâtisserie',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (11,'Caviste',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (12,'Tabac',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (13,'Jouets et jeux',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (14,'Magasin de sport',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (15,'Ameublement et Mobilier',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (16,'Fournitures de Bureaux',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (17,'Mobilier de Bureaux',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (18,'Mobilier de Jardin',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (19,'Vêtements',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (20,'Chaussures',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (21,'Bijoux et accessoires',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (22,'Puériculture',1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (23,'Administrations',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (24,'Ambassades et Consulats',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (25,'Associations, syndicats',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (26,'Douane, Agences',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (27,'Minisères',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (28,'O.N.G & Organisations Internationales',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (29,'Offices Nationaux',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (30,'Poste',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (31,'Sécurité Sociale',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (32,'Institution publique',2,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (33,'Matériels et Produits agricoles',3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (34,'Agricole, Produits Chimiques',3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (35,'Agriculture',3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (36,'Equipements et Matériel agricoles',3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (37,'Agro-Alimentaire',3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (38,'Agro-Industrie',3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (39,'Elevage',3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (40,'Elevage - Consultants',3,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (41,'Abattoirs et Viande en Gros',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (42,'Alcools, vins, spiritueux, drogueries',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (43,'Alimentaire, Distributeurs et Grossistes',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (44,'Industries alimentaires',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (45,'Produits alimentaires',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (46,'Alimentation Animale',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (47,'Alimentation Générale',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (48,'Boissons',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (49,'Boucherie - charcuterie',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (50,'Boulangeries, Patisseries, Glaces',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (51,'Boulangeries, Patisseries, Glaces - matériel & équipement',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (52,'Brasseries',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (53,'Brasseries - matériel & équipement',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (54,'Cacao - Production et Exportation',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (55,'Café - Production et Exportation',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (56,'Catering',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (57,'Distilleries',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (58,'Environnement',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (59,'Gomme Arabique',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (60,'Lait, Yaourt et Fromage',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (61,'Laiteries',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (62,'Minoteries',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (63,'Pêche - Commercialisation et Exportation',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (64,'Pêche - Congelation',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (65,'Sucre, Fabrication et Raffinage',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (66,'Supermarchés',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (67,'Thé - Production et Commercialisation',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (68,'Traiteurs',4,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (69,'Auto-Ecoles',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (70,'Automobiles et Concessionnaires',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (71,'Expertises automobiles',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (72,'Automobiles - Pièces Détachées et Accessoires',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (73,'Voitures d''occasion',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (74,'Constructions Mécaniques',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (75,'Contrôles Techniques',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (76,'Cycles et Motos',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (77,'Engins ee Chantier et Matériels',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (78,'Garages',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (79,'Mécanique Générale',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (80,'Mécanique - Industries',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (81,'Moteurs et Pompes',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (82,'Pneumatiques',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (83,'Tracking',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (84,'Véhicules Industriels',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (85,'Station-service',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (86,'Parking',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (87,'Garage',5,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (88,'Assurances',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (89,'Assurances Vies',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (90,'Assurances médicales',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (91,'Assureurs - Courtiers Et Conseils',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (92,'Banques et Organismes Financiers',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (93,'Equipements de Sécurité Bancaire',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (94,'Banques - Services Mobiles',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (95,'Bureaux de Change et Transferts d''argent',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (96,'Bureaux de Contrôle',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (97,'Cabinets Comptables',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (98,'Centres d''Information',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (99,'Crédits et Finances',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (100,'Enquêtes, recherches et investigation',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (101,'Holdings',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (102,'Investissements',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (103,'Transports de Fonds',6,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (104,'Adduction d''eau et VRD',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (105,'Agencement et Décoration',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (106,'Industrie d''aluminium',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (107,'Aménagement des Terrains Urbains',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (108,'Architecture et Urbanisme',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (109,'Ascenseurs',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (110,'Assainissement et Canalisations',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (111,'Bâches et Stores',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (112,'Bâtiments et Travaux Publics',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (113,'Bâtiments - Expertises',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (114,'Bâtiments - Nettoyage',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (115,'Bâtiments - Préfabriqué',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (116,'Bâtiments - Ravalement',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (117,'Bâtiments - Réhabilitation',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (118,'Bâtiments - Second Œuvre',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (119,'Bitume',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (120,'Bois et Négoce',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (121,'Bois - Industries',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (122,'Bois - Scieries',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (123,'Bricolage',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (124,'Briqueteries',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (125,'Bureaux d''Etudes et D''Ingénierie',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (126,'Câbles',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (127,'Caoutchouc',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (128,'Carrelages',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (129,'Carrières - Exploitations et Exploration',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (130,'Chaudronnerie',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (131,'Cimenteries',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (132,'Citernes - Métallique et Plastique',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (133,'Climatisation',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (134,'Climatisation - Dépannage et Maintenance',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (135,'Constructions Industrielles',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (136,'Constructions Métalliques',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (137,'Développement Rural et Urbain',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (138,'Ebenistes',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (139,'Echafaudages',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (140,'Espaces Verts et Jardins',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (141,'Etanchéité',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (142,'Faux-Plafonds et Staff',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (143,'Fer et Acier',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (144,'Forages',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (145,'Forages - Maintenance',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (146,'Forages - Matériels et Equipements',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (147,'Forestiers - Matériels et Equipement',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (148,'Génie Civil',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (149,'Géologues',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (150,'Géomètres - topographes',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (151,'Groupes Electrogènes',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (152,'Hydraulique',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (153,'Hydraulique - Constructions',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (154,'Hydraulique - Matériels et Equipements',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (155,'Isolation industrielle',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (156,'Laboratoires d''Analyses du Bâtiment',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (157,'Location d''Engins de Chantier',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (158,'Matériaux de Construction',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (159,'Menuiseries Aluminium',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (160,'Menuiseries Bois',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (161,'Menuiseries Industrielles',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (162,'Menuiseries Métalliques',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (163,'Mines - Exploitations et Exploration',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (164,'Mines - Import et Export',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (165,'Mines - Matériels et Equipements',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (166,'Mines - Recherche',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (167,'Miroiteries et Vitreries',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (168,'Ouvrages d''Art',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (169,'Peintres',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (170,'Peinture',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (171,'Piscines',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (172,'Plomberie et Sanitaires',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (173,'Portes et Fenêtres',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (174,'Propreté urbaine',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (175,'Quincailleries',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (176,'Routes',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (177,'Routes - Matériaux',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (178,'Routes - Signalisation',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (179,'Serrureries',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (180,'Toitures - Matériaux',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (181,'Tôles',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (182,'Topographie',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (183,'Travaux Publics et Terrassement',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (184,'Travaux Publics et Terrassement - Maintenance',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (185,'Tuyauteries et PVC',7,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (186,'Coiffeur',8,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (187,'Institut de beauté, parfumerie, relaxation',8,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (188,'Massages',8,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (189,'Centrales d''Achats',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (190,'Chambres de Commerce',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (191,'Commerce Exterieur - Promotion',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (192,'Commerce Général',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (193,'E-Commerce',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (194,'Groupements D''Entreprises',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (195,'Import et Export',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (196,'Promotion Commerciale et Etudes',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (197,'Recouvrements Commerciaux',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (198,'Représentation Commerciale',9,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (199,'Agences de Mannequins',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (200,'Agences de Presse et d''Information',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (201,'Agences de Publicité et de Communication',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (202,'Audiovisuel - Matériels et Production',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (203,'Evénementiel',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (204,'Journaux et Presse',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (205,'Maison d''édition',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (206,'Marketing',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (207,'Objets Publicitaires',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (208,'Organisations de Conférences',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (209,'Radio et Télévision',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (210,'Radio-Communication',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (211,'Relations Publiques et Organisations',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (212,'Ressources Humaines',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (213,'Sérigraphie',10,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (214,'Eau - Distribution',11,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (215,'Eau - Laboratoires d''Analyses',11,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (216,'Eau - Traitement',11,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (217,'Centres de Documentation',12,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (218,'Crèche',12,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (219,'Centre de loisirs d''enfants',12,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (220,'Centre linguistique - enseignement',12,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (221,'Centres de Formation',12,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (222,'Centres de Recherche',12,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (223,'Ecoles et Universités',12,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (224,'Automatisme',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (225,'Batteries et Piles',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (226,'Electricité - Générale et Industrielle',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (227,'Electricité - Expertises',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (228,'Electricité - Industries',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (229,'Electricité - Ingénierie',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (230,'Electricité - Materiels et Equipement',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (231,'Electrification Rurale Et Urbaine',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (232,'Electromécanique',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (233,'Energie',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (234,'Energie Nouvelle et Renouvelable',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (235,'Energie Solaire',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (236,'Gaz Domestique Et Industriel',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (237,'Géotechnique',13,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (238,'Hydrocarbures - Aviation',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (239,'Hydrocarbures - Distribution',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (240,'Hydrocarbures - Equipements Et Mater...',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (241,'Hydrocarbures - Expertises',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (242,'Hydrocarbures - Exploration',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (243,'Hydrocarbures - Logistiques',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (244,'Hydrocarbures - Lubrifiants',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (245,'Hydrocarbures - Maintenance',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (246,'Hydrocarbures - Production',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (247,'Hydrocarbures - Transports',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (248,'Pétroliers, Constructions',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (249,'Pétroliers - Matériels et Equipement',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (250,'Raffineries',14,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (251,'Garde Meubles',15,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (252,'Immobilier - Agences',15,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (253,'Immobilier - Expertises',15,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (254,'Immobilier - Gestion',15,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (255,'Immobilier - Location',15,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (256,'Immobilier - Promoteurs',15,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (257,'Electro-Ménager',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (258,'Electronique',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (259,'Allumettes et Bougies',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (260,'Armes et Munitions',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (261,'Assistance Technique',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (262,'Cartonneries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (263,'Chaussures, Manufactures',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (264,'Coton',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (265,'Dépannage et Maintenance Industrielle',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (266,'Diamant et Or',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (267,'Emballage et Conditionnement',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (268,'Equipements de Bureaux',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (269,'Equipements Industriels',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (270,'Fournitures Industrielles',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (271,'Froid Industriel',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (272,'Location De Matériels',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (273,'Machines-Outils, Manufactures',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (274,'Manutention Industrielle',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (275,'Matelas',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (276,'Matelas, Equipements et Materiels',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (277,'Mesure et Pesage, Materiels',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (278,'Nettoyage Industriel',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (279,'Nettoyage, Matériels et Equipements',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (280,'Papier - Industries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (281,'Pièces Détachées Industrielles',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (282,'Plastique - Industries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (283,'Plastique - Produits',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (284,'Savonneries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (285,'Soudage, Matériels et Produits',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (286,'Tabac, Manufactures et Importateurs',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (287,'Travail Temporaire, Interim',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (288,'Tuyauteries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (289,'Verre - Industries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (290,'Zone Franche Industrielle',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (291,'Ameublement et Mobilier, Industries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (292,'Fournitures de Bureaux, Industries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (293,'Mobilier - Industries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (294,'Chimie - Industries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (295,'Chimie - Produits',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (296,'Parfum, Industries',16,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (297,'Antennes Paraboliques, Equipements',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (298,'Archivage Numerique',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (299,'Bureautique',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (300,'Business Center',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (301,'Centres d''Appels',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (302,'Courriers Express, Colis Express',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (303,'Cyber-Cafes',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (304,'Domiciliation de Sociétés',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (305,'Editeurs',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (306,'Etudes de Marchés',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (307,'Imprimeries',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (308,'Imprimeries, Matériels et Equipement',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (309,'Informatique',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (310,'Informatique - Consommables',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (311,'Informatique - Constructeurs',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (312,'Informatique - Consultants',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (313,'Informatique - Environnement',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (314,'Informatique - Expertises',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (315,'Informatique - Gestion De Maintenance',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (316,'Informatique - Ingénierie',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (317,'Informatique - Ingénieurs',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (318,'Informatique - Maintenance',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (319,'Informatique - Reseaux',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (320,'Informatique - Securite',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (321,'Internet',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (322,'Internet - Provider',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (323,'Internet - Web Design',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (324,'Internet - E-Business & E-Commerce',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (325,'Paratonnerre',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (326,'Technologies Nouvelles',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (327,'Technologies Nouvelles, Consultants',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (328,'Traducteurs Et Interpretes',17,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (329,'Avocats',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (330,'Avocats d''Affaires Internationales',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (331,'Cabinets Juridiques et Fiscaux',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (332,'Consultants',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (333,'Consultants en Immigration',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (334,'Consultants Internationaux',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (335,'Expertises  Comptables, Audit Et Conseil',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (336,'Expertises - Etudes, Communication',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (337,'Expertises Judiciaire',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (338,'Huissiers De Justice',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (339,'Notaires',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (340,'Projets et Bureaux D''Appui',18,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (341,'Artisanat, Antiquaires et Galeries d''Art',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (342,'Cadeaux',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (343,'Casino',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (344,'Cinéma et vidéothèques',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (345,'Centre culturel',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (346,'Musée',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (347,'Musique',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (348,'Théâtre, spectacle',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (349,'Cabaret',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (350,'Bibliothèque et Centre de Documentation',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (351,'Librairie, papeterie',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (352,'Sport',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (353,'Espaces verts et Jardins',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (354,'Salle de spectacles - salle de fêtes',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (355,'Loisirs, jeux et entertainment',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (356,'Loterie',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (357,'Voyance, Medium',19,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (358,'Restaurant',20,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (359,'Night Clubs et Discothèques',20,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (360,'Restauration rapide',20,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (361,'Bar, Café',20,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (362,'Salons de Thé et Glaciers',20,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (363,'Ambulance',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (364,'Assistance sociale',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (365,'Médecine Générale',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (366,'Médecine Spécialisée - dentiste',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (367,'Médecine Spécialisée - dermatologie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (368,'Médecine Spécialisée - cardiologie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (369,'Médecine Spécialisée - oncologie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (370,'Médecine Spécialisée - ophtalmologie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (371,'Médecine Spécialisée - psychologie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (372,'Médecine Spécialisée - angiologie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (373,'Médecine Spécialisée - pédicure et podologie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (374,'Médecine Spécialisée - ostéopathie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (375,'Médecine Spécialisée - gynécologie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (376,'Médecine Spécialisée - kinésithérapeute',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (377,'Médecine naturelle, traditionnelle',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (378,'Médecine du travail',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (379,'Chirurgie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (380,'Chirurgie Esthétique',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (381,'Cliniques et Hopitaux',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (382,'Cosmétiques - Industries',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (383,'Cosmétiques - Produits',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (384,'Drogueries',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (385,'Laboratoires d''Analyses Médicales',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (386,'Laboratoires, Matériels et Equipement',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (387,'Laboratoires - Produits',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (388,'Medical - Assistance',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (389,'Medical - Gaz Medical',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (390,'Medical - Industries',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (391,'Medical - Materiels Et Equipements',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (392,'Medical - Produits',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (393,'Opticiens',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (394,'Opticiens - Matériels et Equipements',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (395,'Para-Pharmacie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (396,'Pharmaceutiques - Distributeurs',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (397,'Pharmaceutiques - Industries',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (398,'Pharmaceutiques - Laboratoires',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (399,'Pharmaceutiques - Materiels Et Equipement',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (400,'Pharmaceutiques - Produits',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (401,'Pharmacies',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (402,'Phytosanitaires - Traitements',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (403,'Urgences Medicales',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (404,'Vétérinaires',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (405,'Vétérinaires, Produits et Pharmacie',21,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (406,'Alarmes Et Surveillance, Matériels électroniques',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (407,'Badges, Fabrication',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (408,'Controles Techniques',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (409,'Détectives',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (410,'Escorte Véhicules',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (411,'Gardiennage et Sécurité',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (412,'Gardiennage et Sécurité - Equipements',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (413,'Incendie et Protection - Matériels',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (414,'Sécurité - Audits et Consultants',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (415,'Télé-Surveillance et Vidéo-Surveillance',22,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (416,'Télécommunications - Transmission de signal',23,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (417,'Télécommunications et Téléphonie',23,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (418,'Télécommunications - Fibres Optique',23,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (419,'Télécommunications - Installation et maintenance',23,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (420,'Télécommunications - Matériels et équipement',23,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (421,'Télécommunications - Mobiles',23,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (422,'Télécommunications - Réseaux',23,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (423,'Télécommunications - Satellite',23,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (424,'Confection, Couture, Broderie',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (425,'Equipements et vêtements militaires',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (426,'Friperies',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (427,'Prêt à Porter - Gros et Détail',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (428,'Textile',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (429,'Textile, Filature, Tissage, Impression',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (430,'Textile, Fournitures',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (431,'Textile - Matériels et Equipements',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (432,'Vêtements  Manufactures',24,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (433,'Agences de Tourisme',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (434,'Centres d''Information',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (435,'Agences de voyage, tours opérateurs',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (436,'Equipements Hôtels et Restaurants',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (437,'Hôtel',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (438,'Auberge',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (439,'Location d''avions',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (440,'Location de bateaux',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (441,'Location de voitures',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (442,'Transport Logistique',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (443,'Transports Touristiques',25,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (444,'Accastillage',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (445,'Acconage',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (446,'Aéronautique',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (447,'Aéronautique - Centrales D''Achats',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (448,'Aéronautique - Maintenance',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (449,'Aéroports',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (450,'Aéroports - Equipements',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (451,'Aéroports -  Maintenance',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (452,'Aéroports -  Securite Aerienne',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (453,'Aéroports -  Services',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (454,'Agences en Douane',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (455,'Agences Maritimes',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (456,'Aéronautique - Pièces Détachées',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (457,'Chantiers Navals',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (458,'Chemin de Fer',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (459,'Compagnies Aériennes',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (460,'Containers, Fabrication et Location',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (461,'Déménagements',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (462,'Expertises Maritimes et Terrestres',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (463,'Fret aérien - maritime & international',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (464,'Manutention et Entreposage',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (465,'Manutention - Equipements',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (466,'Manutention - Portuaire',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (467,'Ports',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (468,'Ports, Matériels et Equipements',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (469,'Shipchandler',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (470,'Transit et Consignation',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (471,'Transports Aériens',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (472,'Transports en Commun',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (473,'Transports Ferroviaires',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (474,'Transports Internationaux',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (475,'Transports Maritimes',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (476,'Transports Routiers',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (477,'Transports Urbains',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (478,'Travaux Maritimes',26,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO sous_categories(id,nom,idCategorie,logoUrl,created_at,updated_at) VALUES (479,'Autres',27,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
