CREATE TABLE IF NOT EXISTS sous_categories(
   id           INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,nom          VARCHAR(191) NOT NULL
  ,id_categorie INTEGER 
);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (1,'Boutiques',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (2,'Brocante',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (3,'Supermarché',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (4,'Epicerie',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (5,'Blanchisseries et Pressings',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (6,'Centre Commercial',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (7,'Maison et Jardin',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (8,'Hifi, téléphonie',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (9,'Fleuriste',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (10,'Boulangerie, Pâtisserie',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (11,'Caviste',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (12,'Tabac',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (13,'Jouets et jeux',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (14,'Magasin de sport',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (15,'Ameublement et Mobilier',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (16,'Fournitures de Bureaux',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (17,'Mobilier de Bureaux',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (18,'Mobilier de Jardin',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (19,'Vêtements',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (20,'Chaussures',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (21,'Bijoux et accessoires',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (22,'Puériculture',1);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (23,'Administrations',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (24,'Ambassades et Consulats',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (25,'Associations, syndicats',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (26,'Douane, Agences',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (27,'Minisères',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (28,'O.N.G & Organisations Internationales',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (29,'Offices Nationaux',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (30,'Poste',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (31,'Sécurité Sociale',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (32,'Institution publique',2);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (33,'Matériels et Produits agricoles',3);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (34,'Agricole, Produits Chimiques',3);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (35,'Agriculture',3);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (36,'Equipements et Matériel agricoles',3);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (37,'Agro-Alimentaire',3);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (38,'Agro-Industrie',3);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (39,'Elevage',3);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (40,'Elevage - Consultants',3);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (41,'Abattoirs et Viande en Gros',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (42,'Alcools, vins, spiritueux, drogueries',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (43,'Alimentaire, Distributeurs et Grossistes',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (44,'Industries alimentaires',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (45,'Produits alimentaires',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (46,'Alimentation Animale',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (47,'Alimentation Générale',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (48,'Boissons',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (49,'Boucherie - charcuterie',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (50,'Boulangeries, Patisseries, Glaces',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (51,'Boulangeries, Patisseries, Glaces - matériel & équipement',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (52,'Brasseries',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (53,'Brasseries - matériel & équipement',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (54,'Cacao - Production et Exportation',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (55,'Café - Production et Exportation',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (56,'Catering',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (57,'Distilleries',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (58,'Environnement',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (59,'Gomme Arabique',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (60,'Lait, Yaourt et Fromage',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (61,'Laiteries',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (62,'Minoteries',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (63,'Pêche - Commercialisation et Exportation',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (64,'Pêche - Congelation',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (65,'Sucre, Fabrication et Raffinage',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (66,'Supermarchés',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (67,'Thé - Production et Commercialisation',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (68,'Traiteurs',4);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (69,'Auto-Ecoles',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (70,'Automobiles et Concessionnaires',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (71,'Expertises automobiles',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (72,'Automobiles - Pièces Détachées et Accessoires',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (73,'Voitures d''occasion',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (74,'Constructions Mécaniques',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (75,'Contrôles Techniques',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (76,'Cycles et Motos',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (77,'Engins ee Chantier et Matériels',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (78,'Garages',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (79,'Mécanique Générale',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (80,'Mécanique - Industries',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (81,'Moteurs et Pompes',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (82,'Pneumatiques',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (83,'Tracking',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (84,'Véhicules Industriels',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (85,'Station-service',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (86,'Parking',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (87,'Garage',5);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (88,'Assurances',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (89,'Assurances Vies',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (90,'Assurances médicales',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (91,'Assureurs - Courtiers Et Conseils',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (92,'Banques et Organismes Financiers',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (93,'Equipements de Sécurité Bancaire',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (94,'Banques - Services Mobiles',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (95,'Bureaux de Change et Transferts d''argent',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (96,'Bureaux de Contrôle',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (97,'Cabinets Comptables',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (98,'Centres d''Information',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (99,'Crédits et Finances',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (100,'Enquêtes, recherches et investigation',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (101,'Holdings',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (102,'Investissements',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (103,'Transports de Fonds',6);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (104,'Adduction d''eau et VRD',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (105,'Agencement et Décoration',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (106,'Industrie d''aluminium',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (107,'Aménagement des Terrains Urbains',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (108,'Architecture et Urbanisme',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (109,'Ascenseurs',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (110,'Assainissement et Canalisations',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (111,'Bâches et Stores',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (112,'Bâtiments et Travaux Publics',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (113,'Bâtiments - Expertises',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (114,'Bâtiments - Nettoyage',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (115,'Bâtiments - Préfabriqué',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (116,'Bâtiments - Ravalement',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (117,'Bâtiments - Réhabilitation',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (118,'Bâtiments - Second Œuvre',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (119,'Bitume',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (120,'Bois et Négoce',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (121,'Bois - Industries',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (122,'Bois - Scieries',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (123,'Bricolage',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (124,'Briqueteries',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (125,'Bureaux d''Etudes et D''Ingénierie',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (126,'Câbles',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (127,'Caoutchouc',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (128,'Carrelages',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (129,'Carrières - Exploitations et Exploration',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (130,'Chaudronnerie',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (131,'Cimenteries',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (132,'Citernes - Métallique et Plastique',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (133,'Climatisation',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (134,'Climatisation - Dépannage et Maintenance',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (135,'Constructions Industrielles',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (136,'Constructions Métalliques',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (137,'Développement Rural et Urbain',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (138,'Ebenistes',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (139,'Echafaudages',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (140,'Espaces Verts et Jardins',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (141,'Etanchéité',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (142,'Faux-Plafonds et Staff',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (143,'Fer et Acier',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (144,'Forages',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (145,'Forages - Maintenance',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (146,'Forages - Matériels et Equipements',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (147,'Forestiers - Matériels et Equipement',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (148,'Génie Civil',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (149,'Géologues',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (150,'Géomètres - topographes',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (151,'Groupes Electrogènes',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (152,'Hydraulique',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (153,'Hydraulique - Constructions',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (154,'Hydraulique - Matériels et Equipements',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (155,'Isolation industrielle',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (156,'Laboratoires d''Analyses du Bâtiment',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (157,'Location d''Engins de Chantier',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (158,'Matériaux de Construction',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (159,'Menuiseries Aluminium',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (160,'Menuiseries Bois',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (161,'Menuiseries Industrielles',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (162,'Menuiseries Métalliques',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (163,'Mines - Exploitations et Exploration',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (164,'Mines - Import et Export',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (165,'Mines - Matériels et Equipements',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (166,'Mines - Recherche',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (167,'Miroiteries et Vitreries',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (168,'Ouvrages d''Art',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (169,'Peintres',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (170,'Peinture',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (171,'Piscines',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (172,'Plomberie et Sanitaires',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (173,'Portes et Fenêtres',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (174,'Propreté urbaine',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (175,'Quincailleries',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (176,'Routes',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (177,'Routes - Matériaux',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (178,'Routes - Signalisation',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (179,'Serrureries',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (180,'Toitures - Matériaux',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (181,'Tôles',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (182,'Topographie',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (183,'Travaux Publics et Terrassement',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (184,'Travaux Publics et Terrassement - Maintenance',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (185,'Tuyauteries et PVC',7);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (186,'Coiffeur',8);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (187,'Institut de beauté, parfumerie, relaxation',8);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (188,'Massages',8);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (189,'Centrales d''Achats',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (190,'Chambres de Commerce',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (191,'Commerce Exterieur - Promotion',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (192,'Commerce Général',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (193,'E-Commerce',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (194,'Groupements D''Entreprises',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (195,'Import et Export',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (196,'Promotion Commerciale et Etudes',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (197,'Recouvrements Commerciaux',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (198,'Représentation Commerciale',9);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (199,'Agences de Mannequins',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (200,'Agences de Presse et d''Information',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (201,'Agences de Publicité et de Communication',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (202,'Audiovisuel - Matériels et Production',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (203,'Evénementiel',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (204,'Journaux et Presse',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (205,'Maison d''édition',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (206,'Marketing',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (207,'Objets Publicitaires',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (208,'Organisations de Conférences',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (209,'Radio et Télévision',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (210,'Radio-Communication',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (211,'Relations Publiques et Organisations',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (212,'Ressources Humaines',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (213,'Sérigraphie',10);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (214,'Eau - Distribution',11);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (215,'Eau - Laboratoires d''Analyses',11);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (216,'Eau - Traitement',11);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (217,'Centres de Documentation',12);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (218,'Crèche',12);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (219,'Centre de loisirs d''enfants',12);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (220,'Centre linguistique - enseignement',12);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (221,'Centres de Formation',12);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (222,'Centres de Recherche',12);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (223,'Ecoles et Universités',12);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (224,'Automatisme',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (225,'Batteries et Piles',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (226,'Electricité - Générale et Industrielle',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (227,'Electricité - Expertises',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (228,'Electricité - Industries',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (229,'Electricité - Ingénierie',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (230,'Electricité - Materiels et Equipement',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (231,'Electrification Rurale Et Urbaine',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (232,'Electromécanique',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (233,'Energie',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (234,'Energie Nouvelle et Renouvelable',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (235,'Energie Solaire',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (236,'Gaz Domestique Et Industriel',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (237,'Géotechnique',13);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (238,'Hydrocarbures - Aviation',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (239,'Hydrocarbures - Distribution',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (240,'Hydrocarbures - Equipements Et Mater...',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (241,'Hydrocarbures - Expertises',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (242,'Hydrocarbures - Exploration',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (243,'Hydrocarbures - Logistiques',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (244,'Hydrocarbures - Lubrifiants',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (245,'Hydrocarbures - Maintenance',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (246,'Hydrocarbures - Production',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (247,'Hydrocarbures - Transports',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (248,'Pétroliers, Constructions',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (249,'Pétroliers - Matériels et Equipement',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (250,'Raffineries',14);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (251,'Garde Meubles',15);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (252,'Immobilier - Agences',15);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (253,'Immobilier - Expertises',15);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (254,'Immobilier - Gestion',15);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (255,'Immobilier - Location',15);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (256,'Immobilier - Promoteurs',15);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (257,'Electro-Ménager',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (258,'Electronique',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (259,'Allumettes et Bougies',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (260,'Armes et Munitions',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (261,'Assistance Technique',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (262,'Cartonneries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (263,'Chaussures, Manufactures',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (264,'Coton',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (265,'Dépannage et Maintenance Industrielle',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (266,'Diamant et Or',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (267,'Emballage et Conditionnement',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (268,'Equipements de Bureaux',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (269,'Equipements Industriels',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (270,'Fournitures Industrielles',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (271,'Froid Industriel',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (272,'Location De Matériels',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (273,'Machines-Outils, Manufactures',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (274,'Manutention Industrielle',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (275,'Matelas',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (276,'Matelas, Equipements et Materiels',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (277,'Mesure et Pesage, Materiels',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (278,'Nettoyage Industriel',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (279,'Nettoyage, Matériels et Equipements',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (280,'Papier - Industries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (281,'Pièces Détachées Industrielles',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (282,'Plastique - Industries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (283,'Plastique - Produits',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (284,'Savonneries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (285,'Soudage, Matériels et Produits',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (286,'Tabac, Manufactures et Importateurs',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (287,'Travail Temporaire, Interim',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (288,'Tuyauteries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (289,'Verre - Industries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (290,'Zone Franche Industrielle',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (291,'Ameublement et Mobilier, Industries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (292,'Fournitures de Bureaux, Industries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (293,'Mobilier - Industries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (294,'Chimie - Industries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (295,'Chimie - Produits',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (296,'Parfum, Industries',16);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (297,'Antennes Paraboliques, Equipements',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (298,'Archivage Numerique',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (299,'Bureautique',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (300,'Business Center',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (301,'Centres d''Appels',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (302,'Courriers Express, Colis Express',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (303,'Cyber-Cafes',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (304,'Domiciliation de Sociétés',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (305,'Editeurs',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (306,'Etudes de Marchés',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (307,'Imprimeries',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (308,'Imprimeries, Matériels et Equipement',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (309,'Informatique',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (310,'Informatique - Consommables',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (311,'Informatique - Constructeurs',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (312,'Informatique - Consultants',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (313,'Informatique - Environnement',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (314,'Informatique - Expertises',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (315,'Informatique - Gestion De Maintenance',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (316,'Informatique - Ingénierie',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (317,'Informatique - Ingénieurs',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (318,'Informatique - Maintenance',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (319,'Informatique - Reseaux',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (320,'Informatique - Securite',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (321,'Internet',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (322,'Internet - Provider',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (323,'Internet - Web Design',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (324,'Internet - E-Business & E-Commerce',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (325,'Paratonnerre',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (326,'Technologies Nouvelles',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (327,'Technologies Nouvelles, Consultants',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (328,'Traducteurs Et Interpretes',17);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (329,'Avocats',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (330,'Avocats d''Affaires Internationales',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (331,'Cabinets Juridiques et Fiscaux',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (332,'Consultants',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (333,'Consultants en Immigration',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (334,'Consultants Internationaux',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (335,'Expertises  Comptables, Audit Et Conseil',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (336,'Expertises - Etudes, Communication',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (337,'Expertises Judiciaire',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (338,'Huissiers De Justice',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (339,'Notaires',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (340,'Projets et Bureaux D''Appui',18);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (341,'Artisanat, Antiquaires et Galeries d''Art',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (342,'Cadeaux',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (343,'Casino',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (344,'Cinéma et vidéothèques',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (345,'Centre culturel',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (346,'Musée',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (347,'Musique',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (348,'Théâtre, spectacle',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (349,'Cabaret',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (350,'Bibliothèque et Centre de Documentation',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (351,'Librairie, papeterie',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (352,'Sport',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (353,'Espaces verts et Jardins',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (354,'Salle de spectacles - salle de fêtes',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (355,'Loisirs, jeux et entertainment',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (356,'Loterie',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (357,'Voyance, Medium',19);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (358,'Restaurant',20);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (359,'Night Clubs et Discothèques',20);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (360,'Restauration rapide',20);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (361,'Bar, Café',20);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (362,'Salons de Thé et Glaciers',20);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (363,'Ambulance',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (364,'Assistance sociale',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (365,'Médecine Générale',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (366,'Médecine Spécialisée - dentiste',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (367,'Médecine Spécialisée - dermatologie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (368,'Médecine Spécialisée - cardiologie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (369,'Médecine Spécialisée - oncologie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (370,'Médecine Spécialisée - ophtalmologie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (371,'Médecine Spécialisée - psychologie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (372,'Médecine Spécialisée - angiologie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (373,'Médecine Spécialisée - pédicure et podologie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (374,'Médecine Spécialisée - ostéopathie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (375,'Médecine Spécialisée - gynécologie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (376,'Médecine Spécialisée - kinésithérapeute',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (377,'Médecine naturelle, traditionnelle',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (378,'Médecine du travail',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (379,'Chirurgie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (380,'Chirurgie Esthétique',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (381,'Cliniques et Hopitaux',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (382,'Cosmétiques - Industries',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (383,'Cosmétiques - Produits',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (384,'Drogueries',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (385,'Laboratoires d''Analyses Médicales',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (386,'Laboratoires, Matériels et Equipement',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (387,'Laboratoires - Produits',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (388,'Medical - Assistance',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (389,'Medical - Gaz Medical',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (390,'Medical - Industries',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (391,'Medical - Materiels Et Equipements',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (392,'Medical - Produits',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (393,'Opticiens',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (394,'Opticiens - Matériels et Equipements',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (395,'Para-Pharmacie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (396,'Pharmaceutiques - Distributeurs',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (397,'Pharmaceutiques - Industries',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (398,'Pharmaceutiques - Laboratoires',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (399,'Pharmaceutiques - Materiels Et Equipement',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (400,'Pharmaceutiques - Produits',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (401,'Pharmacies',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (402,'Phytosanitaires - Traitements',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (403,'Urgences Medicales',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (404,'Vétérinaires',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (405,'Vétérinaires, Produits et Pharmacie',21);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (406,'Alarmes Et Surveillance, Matériels électroniques',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (407,'Badges, Fabrication',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (408,'Controles Techniques',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (409,'Détectives',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (410,'Escorte Véhicules',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (411,'Gardiennage et Sécurité',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (412,'Gardiennage et Sécurité - Equipements',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (413,'Incendie et Protection - Matériels',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (414,'Sécurité - Audits et Consultants',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (415,'Télé-Surveillance et Vidéo-Surveillance',22);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (416,'Télécommunications - Transmission de signal',23);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (417,'Télécommunications et Téléphonie',23);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (418,'Télécommunications - Fibres Optique',23);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (419,'Télécommunications - Installation et maintenance',23);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (420,'Télécommunications - Matériels et équipement',23);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (421,'Télécommunications - Mobiles',23);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (422,'Télécommunications - Réseaux',23);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (423,'Télécommunications - Satellite',23);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (424,'Confection, Couture, Broderie',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (425,'Equipements et vêtements militaires',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (426,'Friperies',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (427,'Prêt à Porter - Gros et Détail',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (428,'Textile',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (429,'Textile, Filature, Tissage, Impression',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (430,'Textile, Fournitures',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (431,'Textile - Matériels et Equipements',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (432,'Vêtements  Manufactures',24);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (433,'Agences de Tourisme',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (434,'Centres d''Information',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (435,'Agences de voyage, tours opérateurs',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (436,'Equipements Hôtels et Restaurants',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (437,'Hôtel',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (438,'Auberge',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (439,'Location d''avions',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (440,'Location de bateaux',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (441,'Location de voitures',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (442,'Transport Logistique',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (443,'Transports Touristiques',25);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (444,'Accastillage',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (445,'Acconage',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (446,'Aéronautique',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (447,'Aéronautique - Centrales D''Achats',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (448,'Aéronautique - Maintenance',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (449,'Aéroports',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (450,'Aéroports - Equipements',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (451,'Aéroports -  Maintenance',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (452,'Aéroports -  Securite Aerienne',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (453,'Aéroports -  Services',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (454,'Agences en Douane',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (455,'Agences Maritimes',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (456,'Aéronautique - Pièces Détachées',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (457,'Chantiers Navals',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (458,'Chemin de Fer',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (459,'Compagnies Aériennes',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (460,'Containers, Fabrication et Location',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (461,'Déménagements',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (462,'Expertises Maritimes et Terrestres',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (463,'Fret aérien - maritime & international',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (464,'Manutention et Entreposage',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (465,'Manutention - Equipements',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (466,'Manutention - Portuaire',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (467,'Ports',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (468,'Ports, Matériels et Equipements',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (469,'Shipchandler',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (470,'Transit et Consignation',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (471,'Transports Aériens',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (472,'Transports en Commun',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (473,'Transports Ferroviaires',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (474,'Transports Internationaux',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (475,'Transports Maritimes',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (476,'Transports Routiers',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (477,'Transports Urbains',26);
INSERT INTO sous_categories(id,nom,id_categorie) VALUES (478,'Travaux Maritimes',26);
