export const environment = {
  firebase: {
    projectId: 'position-79196',
    appId: '1:269614845547:web:595f874631dc534984ab2e',
    databaseURL: 'https://position-79196.firebaseio.com',
    storageBucket: 'position-79196.appspot.com',
    locationId: 'us-central',
    apiKey: 'AIzaSyAGpMhtZOISzv8JM4jfd5pXAyl6FX3Vv0w',
    authDomain: 'position-79196.firebaseapp.com',
    messagingSenderId: '269614845547',
    measurementId: 'G-EH0MWZ5DF8',
  },
  production: true,
  url_backend: 'https://services.position.cm/',
  url_image: 'https://services.position.cm',
  primaryColor: '#05BF95',
  url_position_Api: 'https://services.position.cm/',
  avaible_language: ['fr', 'en'],
  default_language: 'fr',
  //url_frontend:"http://localhost:52748/",
  url_demo: 'https://demo.position.cm/',
};
