version: "3"

services:
  app-service-app:
    container_name: app-service-app
    build: .docker/docker
    image: app-service-app
    depends_on:
      - app-service-mysql
      - app-service-redis
    volumes:
      - ./:/application:cached

  app-service-nginx:
    container_name: app-service-nginx
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
      - .docker/nginx/:/var/log/nginx/
    depends_on:
      - app-service-app
      - app-service-mysql
      - app-service-redis

  app-service-mysql:
    container_name: app-service-mysql
    image: mysql:5.7
    ports:
      - "8001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=position
    volumes:
      - app-service-mysql-data:/var/lib/mysql:cached

  app-service-redis:
    container_name: app-service-redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  app-service-mysql-data:
