version: "3"
services:
    position-api:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: position-service-api
        container_name: api-position
        ports:
            - port_api:80
        volumes:
            - ./:/var/www/html

    position-api-mysql:
        restart: always
        image: mysql:5.7
        container_name: api-position-mysql
        ports:
            - "port_db:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=
        volumes:
            - ./db:/var/lib/mysql
