version: "3"
services:
    position-service-app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: position-service-api
        ports:
            - 6000:80
        volumes:
            - ./:/var/www/html

    position-service-mysql:
        restart: always
        image: mysql:5.7
        ports:
            - "6001:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=api-position
        volumes:
            - ./db:/var/lib/mysql
