version: "3"

services:
    auth-service-app:
        container_name: auth-service-app
        build: .docker/docker
        image: auth-service-app
        depends_on:
            - auth-service-mysql
            - auth-service-redis
        volumes:
            - ./:/application:cached

    auth-service-nginx:
        container_name: auth-service-nginx
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - ./:/application:cached
            - .docker/nginx/:/var/log/nginx/
        depends_on:
            - auth-service-app
            - auth-service-mysql
            - auth-service-redis

    auth-service-mysql:
        container_name: auth-service-mysql
        image: mysql:5.7
        ports:
            - "8001:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=auth
        volumes:
            - auth-service-mysql-data:/var/lib/mysql:cached

    auth-service-redis:
        container_name: auth-service-redis
        image: redis:alpine
        ports:
            - "6379:6379"

volumes:
    auth-service-mysql-data:
